# Generated by Django 5.0.6 on 2024-05-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_program_author_alter_program_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='isVisible',
            field=models.BooleanField(default=True),
        ),
    ]
