# Generated by Django 5.0.6 on 2024-06-18 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_programaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='programaction',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.programaction'),
        ),
        migrations.AlterField(
            model_name='programaction',
            name='action',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('dislike', 'Dislike'), ('heart', 'Heart'), ('comment', 'Comment')], max_length=10, null=True),
        ),
    ]
