# Generated by Django 5.0.6 on 2024-06-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_programaction_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programaction',
            old_name='user',
            new_name='author',
        ),
    ]
