# Generated by Django 5.0.6 on 2024-06-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='actor',
            new_name='author',
        ),
    ]
