# Generated by Django 5.0.6 on 2024-06-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_comment_action_delete_programaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='author',
            new_name='user',
        ),
    ]
