# Generated by Django 5.0.6 on 2024-06-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_user_action_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('share', 'Share'), ('unshare', 'Unshare'), ('love', 'Love'), ('unlove', 'Unlove')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
