# Generated by Django 5.0.6 on 2024-06-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('sent', 'Demande envoyée'), ('accepted', 'Demande acceptée'), ('rejected', 'Demande refusée')], default='sent', max_length=10),
        ),
    ]
