# Generated by Django 5.0.6 on 2024-07-10 14:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_friendship_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='input_type',
            field=models.CharField(default='.txt', max_length=50),
        ),
        migrations.AddField(
            model_name='program',
            name='output_type',
            field=models.CharField(default='.txt', max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='file',
            field=models.FileField(blank=True, default='', upload_to=api.models.get_unique_filename),
        ),
    ]
